### ISSUE TITLE
Menu page not renamed

### ISSUE THREAD

**Issue by HybridMobileApp** [driftyco/ionic-creator-issues#101]
i created two menu pages both have name menu and linking url is /menu . How to make it link menu1 menu2 . so the linking will be /menu1 /menu2

**Comment by matthewkremer** [comment]
We've actually removed that page type for right now. The editing experience was sub-par and buggy. We're talking about how to make complicated editing cases like this better, and will most likely be adding it back in in the future.

Thanks,
Matt
