### ISSUE TITLE
Toggle Developer Mode causes sidebar properties to disappear when switching back to edit

### ISSUE THREAD

**Issue by felix-digitalkarma** [driftyco/ionic-creator-issues#102]
Switching the developer mode toggle from edit to toggle back to edit, after I've selected a page will cause the properties panel to disappear.

Steps to reproduce:
1. Select page under Pages Panel, you should see the properties panel for the selected page
2. Switch the Developer mode toggle from Edit to Test
3. Switch the Developer mode toggle from Test to Edit

Notice how the properties panel disappears on the right. I have to reselect the page for it to show again.

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
