### ISSUE TITLE
Hangs while "Saving"

### ISSUE THREAD

**Issue by mgleason** [driftyco/ionic-creator-issues#105]
1. Dragged out a Header.
2. Dragged out a Spacer
3. Dragged out a Form
4. Dragged out a Toggle.  Note: as I dragged the toggle into the form the two alternated flashing.
5. Added the Title and Name and tried to switch to "Test" mode and it hung - with "Saving" visible at the top of the work area

**Comment by EamonLeonard** [comment]
Same issue - running on 40.0.2214.91 (64-bit) Mac. 
Exporting the code verifies that certain edits were not saved.

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
