### ISSUE TITLE
Loading project shows a blank screen

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-creator-issues#11]
I've got a project with two pages of crap. I opened up the right hand panel and selected the project. I expected it to do nothing, but reloaded the project, which is ok, but it is currently showing a blank page (blank iOS page I mean). The left hand panel shows the right 'tree' of crap I built in - but it appears as if I've lost everything. Clicking on my main page doesn't fix the display. I have to click my *second* page, then back to my first to see it rendered right.

**Comment by matthewkremer** [comment]
Hey Raymond, this should be fixed :+1: Thanks!
