### ISSUE TITLE
The header title don't change

### ISSUE THREAD

**Issue by francotalarico** [driftyco/ionic-creator-issues#110]
I created a login page (at main) and I put a link to another page (Menu) at the "login button".
When I press the login button and go to the menu page, the title header still saying "Login" and the nav menu doesn't have any text.

If I insert the URL directly into the browser resolves the problem, but if I redirected to the page with the button, the bug appears.

![screenshot from 2014-11-13 00 22 26](https://cloud.githubusercontent.com/assets/1689252/5022830/408bba12-6acb-11e4-9632-488c569a2e98.png)
![screenshot from 2014-11-13 00 22 33](https://cloud.githubusercontent.com/assets/1689252/5022831/4092f944-6acb-11e4-8269-e092a841c31c.png)
![screenshot from 2014-11-13 00 22 46](https://cloud.githubusercontent.com/assets/1689252/5022832/40948340-6acb-11e4-90f4-b31b6677bea8.png)
![screenshot from 2014-11-13 00 22 52](https://cloud.githubusercontent.com/assets/1689252/5022834/409e3e4e-6acb-11e4-83fd-527a06c1885e.png)
![screenshot from 2014-11-13 00 22 53](https://cloud.githubusercontent.com/assets/1689252/5022833/409d3198-6acb-11e4-881f-22c81ca2afc7.png)

**Comment by matthewkremer** [comment]
We've actually removed the side-menu page type for right now. The editing experience was sub-par and buggy. We're talking about how to make complicated editing cases like this better, and will most likely be adding it back in in the future.

Thanks,
Matt
