### ISSUE TITLE
workspace out of sync

### ISSUE THREAD

**Issue by FrancisVarga** [driftyco/ionic-creator-issues#114]
if someone wanna look into this repro:
http://creator.ionic.io/app/designer/c0b03e85069c

when i'm exporting the project and look into the code there are double page10 this is not possible and that's why i can't create a new page or even sometimes deleting goes wrong. i don't kow how this gonna happen, but i think there was a state which was not saved and i change it on another browser and added a page, this got a conflict and couldn't merge or has a weird state from now.

**Comment by matthewkremer** [comment]
There was an issue with ID generation that should be fixed in the new major release from Tuesday. Please let me know if you still encounter this problem (existing projects may still be wonky, you may have to delete a page and try again or create a new project).

Thanks,
Matt
