### ISSUE TITLE
Can't add any element

### ISSUE THREAD

**Issue by danilo-valente** [driftyco/ionic-creator-issues#118]
I'm trying to add a Textarea element to a blank page, but an error is logged to my console. This is the stack trace:

```
Uncaught TypeError: Cannot read property 'className' of undefined ionic-creator.js?8:2
    create ionic-creator.js?8:2
    createComponent ionic-creator.js?8:2
    tt ionic-creator.js?8:3
    ft ionic-creator.js?8:4
```

Btw, i'm running on Chromium 37.0.2062.120 64 bits for Ubuntu 14.04

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
