### ISSUE TITLE
Duplicate parameter name

### ISSUE THREAD

**Issue by danilo-valente** [driftyco/ionic-creator-issues#119]
There is a duplicate parameter name `e` on the implementation of factory `DocumentPersistence`:

```javascript
.factory("DocumentPersistence",["$http","$q","$templateCache","$compile","$rootScope","$http","DocumentExporter","Config",function(e,t,n,o,r,e,i,a){
```

This happened because `$http` service is being injected twice and during the minification `$http` is replaced with `e`. Just remove the one of them:

```javascript
.factory("DocumentPersistence",["$http", "$q", "$templateCache", "$compile", "$rootScope", "DocumentExporter", "Config", function($http, $q, $templateCache, $compile, $rootScope, DocumentExporter, Config) {
```

**Comment by matthewkremer** [comment]
Deploying a fix for this sometime today, thanks for catching!

Matt
