### ISSUE TITLE
when adding a page, then selecting it in the hierarchy, no options are shown in the properties view on the right

### ISSUE THREAD

**Issue by lorenjerickson** [driftyco/ionic-creator-issues#122]
Start with a blank project, added a login page.  On that page I can see properties when selecting the page in the hierarchy view, title, routing url, etc.  Add another page, I chose side menu (haven't tried with other page types).  Now when I select the new page in the hierarchy view, I get no properties on the right, only a delete page button.   The page is also rendered with no header, but has room for where the header should be.

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
