### ISSUE TITLE
Ionic Creator > Back > Forward -- Leaves Signup Window

### ISSUE THREAD

**Issue by danielrasmuson** [driftyco/ionic-creator-issues#125]
![screen shot 2014-11-15 at 4 22 30 pm](https://cloud.githubusercontent.com/assets/4013767/5059512/a76fb6c4-6ce3-11e4-832e-79c70c025da7.png)

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt

**Comment by danielrasmuson** [comment]
:+1:
