### ISSUE TITLE
Image element can't be sizes

### ISSUE THREAD

**Issue by shaulhadar** [driftyco/ionic-creator-issues#129]
Hi. I tried to put an image, and i put an image source, but there is no place to style there height and width, or maybe i didn't see it.

I would be happy to know if there is anything to do?

Thanks .

**Comment by irthos** [comment]
+1

**Comment by matthewkremer** [comment]
I've defaulted images to 100% x auto sizing and added the ability to change the height and width of them. Please let me know if this is still an issue for you. Thanks! :+1:

**Comment by shaulhadar** [comment]
Thanks Matthew, looks Good :)
