### ISSUE TITLE
Tabs don't change header title

### ISSUE THREAD

**Issue by shaulhadar** [driftyco/ionic-creator-issues#130]
Hi, I am not sure if this is a bug, but i tried creating a new tabs theme, but when i change the tabs, the header stays the same text, and doesn't show that it changed the tab, only the content changes..

Thanks.

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
