### ISSUE TITLE
Exports don't have dependencies

### ISSUE THREAD

**Issue by shaulhadar** [driftyco/ionic-creator-issues#131]
Hi, when exporting the project from creator, i get only an index.html

I can use it, but there are all the dependencies in the head section, and none of the files, so everytime you download, you need to connect if with the dependencies.  so the file won't actually work until than.

Though i know how to do this, i was wandering if you would consider adding these somehow dynamically in the exported projects?

Thanks for your time :).

**Comment by matthewkremer** [comment]
We now have a multi-file zip export that can be dropped into the WWW directory of an existing Ionic App, and have removed some of the "wierd" dependencies.

Thanks,
Matt
