### ISSUE TITLE
Tab icon gets deleted when navigation again to the <tab> element

### ISSUE THREAD

**Issue by shaulhadar** [driftyco/ionic-creator-issues#132]
Hi, I have found another bug.
When using the tabs template, you can edit which icon you want to each tab, this works great.
The bug happenes when you choose all your icons, than continue editing, and than if you press on the <tab> element to go to its view, the icon of the tab gets deleted and you need to choose it again.

Please check if you can see this as well.

THanks.

**Comment by doctoroakin** [comment]
Im not sure there is a fix for this, maybe they are just taking all of this feedback and plan to incorporate that into a release

**Comment by matthewkremer** [comment]
Closing all duplicate "icon tabs" issues and moving conversation to #26, this is high on my priority list.
