### ISSUE TITLE
When starting with the Side Menu template, there is no header bar on the first page

### ISSUE THREAD

**Issue by shaulhadar** [driftyco/ionic-creator-issues#135]
Hi Ionic Team, I have found a bug in the sidemenu template in ionic creater.
The first page, doesn't have a header bar, which looks inconsistent with the other pages.   Please fix this so it will look like it should, or maybe add a header bar in the components, because currently you can't really use this template without the header..

Thanks for your time :)

**Comment by matthewkremer** [comment]
We've actually removed that page type for right now. The editing experience was sub-par and buggy. We're talking about how to make complicated editing cases like this better, and will most likely be adding it back in in the future.

Thanks,
Matt
