### ISSUE TITLE
Missing Dependancy In Exported Project

### ISSUE THREAD

**Issue by shaulhadar** [driftyco/ionic-creator-issues#137]
Hello Ionic Team.  When exporting a project, the index.html has this dependancy:

<link href="/css/preview-frame.css" rel="stylesheet">

I can change all the other dependancies, but i have no reference from where i am supposed to bring this one.  

Can anyone help clarify for me what needs to be done with this css file?

Thanks,
Shaul.

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
