### ISSUE TITLE
dropping a control onto the page that comes with my new project doesn't work

### ISSUE THREAD

**Issue by csells** [driftyco/ionic-creator-issues#138]
I drag a control onto the page I get after I create my project and the control just goes nowhere, i.e. it doesn't show up on my page. I'm using Chrome for the Mac as my browser.

**Comment by matthewkremer** [comment]
Hey @csells, some components require a specific parent component that they be dropped into, like forms. Which component were you having trouble with? Thanks!

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
