### ISSUE TITLE
Can't scroll down to see other components to drop in

### ISSUE THREAD

**Issue by peterbe** [driftyco/ionic-creator-issues#139]
![screenshot 2014-11-20 09 59 35](https://cloud.githubusercontent.com/assets/26739/5130004/fd397944-709b-11e4-87aa-fc441b47a00b.png)

Using Firefox 35. I can see that there are more components in the navbar on the left but I can't scroll down to see them.

**Comment by jezmck** [comment]
Duplicate: https://github.com/driftyco/ionic-creator-issues/issues/172

**Comment by matthewkremer** [comment]
Closed with #123 :)
