### ISSUE TITLE
Menu icon does not come at top left corner when we select Side Menu type of page

### ISSUE THREAD

**Issue by ukotdiya** [driftyco/ionic-creator-issues#141]
Menu icon does not come at top left corner when we select Side Menu type of page. This is standard practice to show three line menu icon on top left corner for slide in and slide out of side menu

**Comment by softBarbarian** [comment]
same here +1

**Comment by matthewkremer** [comment]
We've actually removed that page type for right now. The editing experience was sub-par and buggy. We're talking about how to make complicated editing cases like this better, and will most likely be adding it back in in the future.

Thanks,
Matt
