### ISSUE TITLE
Back button on header breaks the click URL link

### ISSUE THREAD

**Issue by cqvf76** [driftyco/ionic-creator-issues#142]
I have a first page. where I have click button which link to 2nd page which tabbed view. (linked to 1st tab of 2nd page)

click on button of first page.
it opens the tab1 of 2nd page
click on back button on header
navigates to 1st page
click on button of 1st page
it does not navigate again to tab1 of 2nd page again. (failed) refresh gain works

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
