### ISSUE TITLE
How to link new pages to sidemenu (open sidemenu on drag from new page)

### ISSUE THREAD

**Issue by programming-kid** [driftyco/ionic-creator-issues#144]
i really can't understand how to link new pages to side menu , when new page is created in sidemenu project, i cant drag from left to open side menu as seen in this demo https://github.com/driftyco/ionic-starter-sidemenu

**Comment by matthewkremer** [comment]
We've actually removed that page type for right now. The editing experience was sub-par and buggy. We're talking about how to make complicated editing cases like this better, and will most likely be adding it back in in the future.

Thanks,
Matt
