### ISSUE TITLE
Project not deleted

### ISSUE THREAD

**Issue by shlomis** [driftyco/ionic-creator-issues#145]
Created a test project, tried deleting it entered "yes" or "YES" clicked OK. nothing happened.
project ID "256ff1a8401a"
![image](https://cloud.githubusercontent.com/assets/1629257/5281568/7f702bc2-7b07-11e4-99d9-05e363859ea6.png)

**Comment by bhargavy** [comment]
I'm having the same issue, Project is not being being deleted.

**Comment by matthewkremer** [comment]
Duplicate of #57
