### ISSUE TITLE
Can't remove a button,

### ISSUE THREAD

**Issue by PvUtrix** [driftyco/ionic-creator-issues#147]
I have a button, which I cannot remove and it's acting weird, if I drag it, it gets cloned and the original stays put.

project c716df8301e3
5th screen

**Comment by matthewkremer** [comment]
I'm assuming this may have been an ID issue, many of which were fixed in the new major release that came out Tuesday. Please confirm if you still have this issue (you may have to actually delete button or start a new project to make sure you're button does not have a duplicate ID).

Thanks,
Matt
