### ISSUE TITLE
Hided components on left menu  

### ISSUE THREAD

**Issue by sfadiga** [driftyco/ionic-creator-issues#151]
Description
  Some of the components of the left menu are hided by the page layout, 
  there is no way to access them since an scroll bar is not available and changin screen size does not help either.

Platforms
  Firefox 34.0.5, IE 11.0.9600.17501

Steps to reproduce
  - Log in into the system
  - Create a new project
  - On the main screen (design screen) look at the components menu on the left side of the page
  - Verify the occlusion of some of the components

Regards,
Sandro.

**Comment by jezmck** [comment]
Duplicate: https://github.com/driftyco/ionic-creator-issues/issues/172

**Comment by matthewkremer** [comment]
Closed with #123 :)
