### ISSUE TITLE
Input Label Should Dissappear

### ISSUE THREAD

**Issue by jacobscarter** [driftyco/ionic-creator-issues#154]
I think If you remove the label text from the input the span should be removed or width set to 0.  Otherwise your input looks very off center.

so this:

    <label class="item item-input">
        <span class="input-label"></span>
        <input type="text" placeholder="Username">
    </label>

would become:

    <label class="item item-input">
        <input type="text" placeholder="Username">
    </label>

**Comment by matthewkremer** [comment]
Great idea, just did this :)
