### ISSUE TITLE
Builder Canvas Goes Blank

### ISSUE THREAD

**Issue by jacobscarter** [driftyco/ionic-creator-issues#155]
I was working in my project, clicked the main hamburger menu in the upper right of the screen, clicked on my project (the one I had currently open) and the canvas went blank.

If I clicked on the canvas anywhere these errors were thrown by the console:

    Can't find any component with id null     -> ionic-creator.js?8:3
    Uncaught TypeError: Cannot read property 'isChildOf' of undefined     -> ionic-creator.js?8:3 

I also could not drag anything onto the canvas

My side menu (component tree?) was still there, and I could click on the components (markdown for example) and the options for that component would appear on the right sidebar, correctly populated.

However the children of my form component (two inputs) labels disappeared, the menu would still expand to make room for them, but I could not see their labels.  I could click the blank space and it would properly populate the right sidebar with the data for each input.

**Comment by matthewkremer** [comment]
We've actually removed that page type for right now. The editing experience was sub-par and buggy. We're talking about how to make complicated editing cases like this better, and will most likely be adding it back in in the future.

Thanks,
Matt
