### ISSUE TITLE
Tab icons disappear when click the tab tree

### ISSUE THREAD

**Issue by moikzz214** [driftyco/ionic-creator-issues#156]
![error](https://cloud.githubusercontent.com/assets/9510596/5453428/9c63f4c8-8540-11e4-8003-0020846219e0.jpg)

....Also, when I want to put something on 2nd or 3rd tab the content of the 1st tab will show

**Comment by matthewkremer** [comment]
Closing all duplicate "icon tabs" issues and moving conversation to #26, this is high on my priority list.
