### ISSUE TITLE
Components panel doesn't let you scroll down in firefox

### ISSUE THREAD

**Issue by shaulhadar** [driftyco/ionic-creator-issues#158]
Hello Ionic Team.
When using creator in firefox, if you look at the components, you can't scroll down to see all of them.

In chrome it works great, though.

Thanks :)

**Comment by jezmck** [comment]
Duplicate: https://github.com/driftyco/ionic-creator-issues/issues/172

**Comment by matthewkremer** [comment]
Closed with #123 :)
