### ISSUE TITLE
Creating more than 10 pages

### ISSUE THREAD

**Issue by trauzti** [driftyco/ionic-creator-issues#163]
Creating more than 10 pages does not work.
The next new page becomes identical to the last page and messes it up.

**Comment by zronyj** [comment]
I had the same issue, but with 6 pages. All of them from the Blank template. I tried creating other kinds of pages, and everything was fine, but I still can't create the 7th Blank page.

**Comment by zammitt** [comment]
I'm having the same problem.  I have 1 tab page and 6 blank pages.   However, when I create any type of page it displays as the 6th blank page created and everything is all.... strange.

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
