### ISSUE TITLE
Error logging in: Error: connect ETIMEDOUT when using ionic upload

### ISSUE THREAD

**Issue by okpatil4u** [driftyco/ionic-creator-issues#166]
Getting above mentioned error when trying login for upload. Using correct username and password

**Comment by hemgui** [comment]
I have the same issue.
I'm behind a proxy and I have set PROXY environment variable before "ionic start"

Is there any other changes to upload behind a proxy ?

Thanks

**Comment by ivancamilov** [comment]
I'm getting the same error, and I'm not behind any proxies.

**Comment by ivancamilov** [comment]
Oops, turns out the problem (in my case) was an outdated version of `ionic-cli`. I just did a `sudo npm update -g ionic` and everything worked.

**Comment by mikeLspohn** [comment]
I've tried this and I'm still getting username password incorrect error. I've verified it's right by logging into the apps ionic io site. Any ideas? My Ionic CLI version is 1.5.4

**Comment by 8026787** [comment]
same problem

**Comment by matthewkremer** [comment]
Can anyone confirm that this is still an issue? The entire login system has been redone.

Thanks,
Matt

**Comment by ivancamilov** [comment]
I no longer have the issue. I would recommend anyone having this issue still to update ionic (by running `sudo npm update -g ionic`).

**Comment by matthewkremer** [comment]
Thanks @ivancamilov ! :)
