### ISSUE TITLE
Page title doesn't change when changing tab

### ISSUE THREAD

**Issue by shaulhadar** [driftyco/ionic-creator-issues#167]
Hi Ionic Team, I saw you fixed the tabs icon bug! great job :)
But i also noticed that when i switch tabs, the page's title stays at "home", and doesn't change to the tab's title.  

Please fix this..

Thanks...

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
