### ISSUE TITLE
Can't add or delete tab

### ISSUE THREAD

**Issue by shaulhadar** [driftyco/ionic-creator-issues#168]
Hi Ionic Team, I don't see where i can add or delete a tab.
Please add this functionality to creator.

Thanks :)

**Comment by matthewkremer** [comment]
Added this in :+1: 

Just click on your page that contains tabs, then click on the "tabs" element in the left sidebar and you should see a button on the right that says "Add New Tab" :smile: 

You can delete a tab by clicking on it and then clicking on the "x" in the upper right hand corner of the selected outline.
