### ISSUE TITLE
Side Menu Template Is Broken

### ISSUE THREAD

**Issue by shaulhadar** [driftyco/ionic-creator-issues#169]
Hello Ionic Team.
When adding a new side menu project from scratch, you get the project, but you can't add any element, and nothing works when you try to drag and drop it in the screen, please check this...

**Comment by clickonchris** [comment]
I can't figure out how to get the side menu to work either.  +1

**Comment by Camaromelt** [comment]
It looks like the menu is there but the z-index isn't modified so the content remains hidden and cannot be modified.

**Comment by alifjamaluddin** [comment]
You can figure out side menu by click and drag the page to the right. It works exactly like side menu, but with no menu button.

**Comment by MilosStanic** [comment]
I don't have a clue how to make the side menu appear from other pages of the app. I tried click and drag to the right, and the menu doesn't appear. 
It would be useful to add menubar component that can be inserted to every page with a hamburger button.

**Comment by matthewkremer** [comment]
We've actually removed that page type for right now. The editing experience was sub-par and buggy. We're talking about how to make complicated editing cases like this better, and will most likely be adding it back in in the future.

Thanks,
Matt
