### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by viniciusbiz** [driftyco/ionic-creator-issues#171]
When navigate between tabs:

- icons disappear when click over tabname
- add new elements between tabs always return to first tab

**Comment by marcpope** [comment]
I can't even create an extra tab. This thing is not even close to ready.

**Comment by matthewkremer** [comment]
@viniciusbiz I believe this has been fixed, please let me know if you're still having issues otherwise I'll close this in a bit. Thanks!
