### ISSUE TITLE
Can not scroll down in chrome

### ISSUE THREAD

**Issue by S-Burns** [driftyco/ionic-creator-issues#172]
When components extend past the standard page length(in chrome) the scroll bar is not present

**Comment by TwistedDigits** [comment]
Same in FF 34.0.5

**Comment by jezmck** [comment]
Same in `Firefox Developer Edition 36.0a2 (2015-01-12)`.

**Comment by AnthonyCorrado** [comment]
ion-content does not scroll on initial view. Changing states (using tabs), then clicking back to the original broken scroll page makes scrolling work flawlessly. Strangely, the '-webkit-transform: translate3d' shows motion in both instances.

**Comment by matthewkremer** [comment]
Fixed & closed with #70 :+1: Let me know if you're still having any issues!
