### ISSUE TITLE
Resizing images and upload images

### ISSUE THREAD

**Issue by adnbsr** [driftyco/ionic-creator-issues#174]
Currently these properties are not available

**Comment by AntonVoltchok** [comment]
I ran into that too when I logged in to check it out for fun. It's bare-bones right now, but there's at least some stuff you can do as a work-around. For example, if you use their HTML element, it will let you drop a DIV in and they also give you a little code panel. Just physically type the code, and set width="100%" (or any number) after the src and there you go, images that scale to device. 

So at least there's that way until the awesome dudes at ionic release more updates.
![ionichtmltag](https://cloud.githubusercontent.com/assets/7807131/6451853/6f6c9826-c0ff-11e4-8611-dea2f2766b4d.PNG)

**Comment by kfbishop** [comment]
I did see a video where the user used a placeholder URL for images.   While I'd still like to upload actual images, this did help visualize the view.

Example: http://placehold.it/300x150

![screen shot 2015-04-18 at 9 47 43 am](https://cloud.githubusercontent.com/assets/300008/7215657/006a537a-e5b0-11e4-8361-0de1ef6ef511.png)

**Comment by matthewkremer** [comment]
I've defaulted images to 100% x auto sizing and added the ability to change the height and width of them. Please let me know if this is still an issue for you. Thanks! :+1:
