### ISSUE TITLE
Can't set uri for "modal" page

### ISSUE THREAD

**Issue by dillonkrug** [driftyco/ionic-creator-issues#176]
For other layouts, the options have a Routing field, but when I click on the modal header there is no option.

Related to #99 I'm guessing

**Comment by romuloctba** [comment]
+1

**Comment by lucashattori** [comment]
+1

**Comment by matthewkremer** [comment]
We've actually removed the Modal type for right now. The editing experience was sub-par and buggy. We're talking about how to make complicated editing cases like this better, and will most likely be adding it back in in the future.

Thanks,
Matt
