### ISSUE TITLE
Many ng-template files in one index.html, split it please

### ISSUE THREAD

**Issue by linagee** [driftyco/ionic-creator-issues#177]
I'd like my output as individual files, not all in one index.html where I have to break it apart. There doesn't seem to be an automated tool to break apart ng-templates. (But there are gulp modules available to combine into one massive ng-template file.) I'm not sure if maybe I'm doing this wrong or what?

**Comment by aaronksaunders** [comment]
definitely feel this issue should be addressed, it just is not manageable for a complex application

**Comment by matthewkremer** [comment]
Hey @linagee and @aaronksaunders,

Everything is now in a multiple-file zip export that I think you're really going to like! It's organized exactly like you'd organized a real Ionic app.

Thanks,
Matt
