### ISSUE TITLE
[ FORM COMPONENT ] Error while setting forms action and method

### ISSUE THREAD

**Issue by lplume** [driftyco/ionic-creator-issues#181]
After setting forms action and (or) method it hangs on saving (similar to driftyco/ionic-creator-issues#105 )

to reproduce:
1. a the form component
2. try to set it´s action or method

if you need more info (browser, os, log etc) feel free to ask

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
