### ISSUE TITLE
Bottom Tabs Bar Button's Icons Fly Alway 

### ISSUE THREAD

**Issue by MarlonGrape** [driftyco/ionic-creator-issues#183]
When I set right the bottm tabs bar button's icon, and then choose the tabs button again in the left page navigator, the icon of the button will disappear, I had to set it again!

**Comment by mrzmyr** [comment]
+1

**Comment by matthewkremer** [comment]
Closing all duplicate "icon tabs" issues and moving conversation to #26, this is high on my priority list.
