### ISSUE TITLE
Log In link redirect to a wrong page at homepage of Ionic Creator

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-creator-issues#184]
> Down below "https://creator.ionic.io/" In this page "Log in" link redirects to "http://drifty.com/" whether it should redirect to this "https://creator.ionic.io/app/login" link.

> That's all thanks :)

https://github.com/driftyco/ionic/issues/2995

**Comment by mlynch** [comment]
It's really the image at the bottom peaking through, we need to fix that.

On Mon, Jan 26, 2015 at 3:23 PM, Adam Bradley <notifications@github.com>
wrote:

> Down below "https://creator.ionic.io/" In this page "Log in" link
> redirects to "http://drifty.com/" whether it should redirect to this "
> https://creator.ionic.io/app/login" link.
>
> That's all thanks :)
>
> driftyco/ionic#2995 <https://github.com/driftyco/ionic/issues/2995>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-creator-issues/issues/184>.
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/
