### ISSUE TITLE
Tab icons are disappearing

### ISSUE THREAD

**Issue by jayrmotta** [driftyco/ionic-creator-issues#185]
When I select an icon an then change to another tab the previous icon just disappear

**Comment by bluesliverx** [comment]
I've just noticed the same problem.

**Comment by nicksmetBagaar** [comment]
Just noticed it to

**Comment by darshilv** [comment]
Found the same problem

**Comment by supermarcos** [comment]
Me too.

Just in case it is helpful: It is happening here (ionic-creator.js):
i.dataset.tapDisabled = !0, r ? r.$rendered = i : console.error("Couldn't identify component for", i.getAttribute("data-componentid"))
r, there, is undefined. Maybe it shouldn't...

Thanks!

**Comment by mlynch** [comment]
Thanks for digging in a bit. We are in the process of rehauling creator,
but no eta on that. This fix will be in there!

On Wed, Mar 4, 2015 at 9:23 PM, Marcos Morales Rodrigo <
notifications@github.com> wrote:

> Me too.
>
> Just in case it is helpful: It is happening here (ionic-creator.js):
> i.dataset.tapDisabled = !0, r ? r.$rendered = i : console.error("Couldn't
> identify component for", i.getAttribute("data-componentid"))
> r, there, is undefined. Maybe it shouldn't...
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/driftyco/ionic-creator-issues/issues/185#issuecomment-77299702>
> .
>



-- 
Max Lynch
CEO and Co-founder
http://ionicframework.com/

**Comment by jonaldomo** [comment]
+1, arrgh!

**Comment by matthewkremer** [comment]
Closing all duplicate "icon tabs" issues and moving conversation to #26, this is high on my priority list.
