### ISSUE TITLE
Can't delete projects

### ISSUE THREAD

**Issue by SefaOray** [driftyco/ionic-creator-issues#188]
Trying to delete a project returns this exceptions:

 POST https://apps.ionic.io/api/v1/creator/41b469cde197 
41b469cde197:1 XMLHttpRequest cannot load https://apps.ionic.io/api/v1/creator/#ProjectCodeHere#. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://creator.ionic.io' is therefore not allowed access. The response had HTTP status code 520.

**Comment by matthewkremer** [comment]
Closed as a duplicate of #57 :)
