### ISSUE TITLE
Log in href error

### ISSUE THREAD

**Issue by cyberdak** [driftyco/ionic-creator-issues#196]
in https://creator.ionic.io/ the a tag "log in" should herf to "https://creator.ionic.io/app/login",but it href to "http://drifty.com/" now. This error always make me think the creator is uncompleted.

**Comment by bensperry** [comment]
I'm not seeing that. It is still linking to https://creator.ionic.io/app/login as far as I can see.

![image](https://cloud.githubusercontent.com/assets/519526/6398411/029ba2d8-bdb1-11e4-96b0-01ac89feff58.png)

**Comment by cyberdak** [comment]
![image](https://cloud.githubusercontent.com/assets/10494715/6419320/11770aee-bef7-11e4-973b-d8d74dfe0ae8.png)
![creator](https://cloud.githubusercontent.com/assets/10494715/6419352/4583ba6c-bef7-11e4-8b6a-355386d42a65.png)
you can see it .

**Comment by cyberdak** [comment]
btw,maybe it's because i visit from china?Is any cdn network works error?

**Comment by Calzzetta** [comment]
@cyberdak I have the same problem here. That happens because the <footer> is over the <p class="login-text">. @bensperry Try another screen resolution (1366x768) and you have the same problem.

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
