### ISSUE TITLE
Wire up the close button in a modal

### ISSUE THREAD

**Issue by jdforsythe** [driftyco/ionic-creator-issues#198]
Related to #176 and #99 the modal isn't really functional in that you can't customize the route to it, can't name it in the list, and there doesn't appear to be a way to wire up the close button, because the link selection doesn't contain any close method.

**Comment by matthewkremer** [comment]
We actually removed Modal from the new major release on Tuesday. It was just too buggy. We're talking about how to make these more complicated editing functions easier, and will most likely add it back in in the future.

Thanks,
Matt
