### ISSUE TITLE
Project name should have more space

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-creator-issues#20]
I renamed my project to HelloWorld1<b>Injecttest</b> (yes, I was trying to inject crap) and noticed it was shortened in the view:

Screenshot: https://www.evernote.com/shard/s3/sh/146db826-b213-4d1e-98db-037962955cc9/31ca9b0ec40aae7fd10d4ddba416c206

It is a minor quibble but I'd give project titles a bit more room.

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
