### ISSUE TITLE
Delete tab UI not displaying correctly in Chrome v41.0.2272.118 m (64-bit), Windows 8.1

### ISSUE THREAD

**Issue by rtpHarry** [driftyco/ionic-creator-issues#206]
As you can see in the screenshot below the outline that has the option to delete a tab is not displaying correctly in Chrome v41.0.2272.118 m (64-bit), Windows 8.1.

When I click on the tabs directly I don't see any UI outline but if I select it from the hierarchy to the left the selection outline appears collapsed in the far left of the row no matter which tab I select.

![image](https://cloud.githubusercontent.com/assets/1038062/7069280/b82d6e4e-decf-11e4-9613-39a37aa66eef.png)

**Comment by matthewkremer** [comment]
This has been fixed! Thanks :+1:
