### ISSUE TITLE
Side Menu Page doesnt have form to change its attributes

### ISSUE THREAD

**Issue by alamops** [driftyco/ionic-creator-issues#208]
There is a way to edit Side Menu Page attributes?

Example:
I want to change the URL, name, etc.

**Comment by maniappan** [comment]
Creating multilevel selection menu's is difficult without knowing which side menu page to link in the previous menu(all of them have url as menu), so it is needed.

**Comment by matthewkremer** [comment]
Hey,

We actually removed the side-menu from the new release of Creator. It was just too buggy to use. We're looking into ways to make this process easier, and will most likely add it back in in the future.

Thanks,
Matt
