### ISSUE TITLE
Need visual indicator of Main landing view, and ability to change

### ISSUE THREAD

**Issue by kfbishop** [driftyco/ionic-creator-issues#212]
Its currently impossible to know what the main landing view is, without code inspection.  Its also not possible to alter this view to another view.

**Comment by matthewkremer** [comment]
Hey @kfbishop,

We added a "pin" feature to the new version of Creator that launched on Tuesday. When a page is selected, just click the "pin" in the left pane to set it as your landing view.

Thanks,
Matt
