### ISSUE TITLE
Download Missing Assets

### ISSUE THREAD

**Issue by d1b1** [driftyco/ionic-creator-issues#213]
The download feature (great). does not include the required assets to actual run ionic. Maybe the docs are off, but I expected that I would get a dump of the UI views, with the assets to run it all.

**Comment by matthewkremer** [comment]
Hey @d1b1,

At the moment it may be easier to download your project using the CLI to get started with a full environment :) Have you tried doing that yet? If you click on the download button in Ionic Creator, it will show you the command you need to run to download your app and create an entire Ionic project for it locally.

Thanks,
Matt
