### ISSUE TITLE
Tabs icon lost in edit mode

### ISSUE THREAD

**Issue by sgulci** [driftyco/ionic-creator-issues#215]
in tabs page when i click tabs in Page side container icons get invisible

![ioniccreatorbug](https://cloud.githubusercontent.com/assets/3424995/7364046/9bdb70dc-ed8a-11e4-926a-ab30a3ac4228.png)

**Comment by erinmays** [comment]
seconded

**Comment by novarac23** [comment]
Yep. And I can not post different content on different pages of tabs because it always pulls me back to the first tab.

**Comment by aloncarmel** [comment]
same here. SUPER annoying.

**Comment by matthewkremer** [comment]
Duplicate of #26, this is definitely high on my list to look into.
