### ISSUE TITLE
No way to upload a new project to Creator

### ISSUE THREAD

**Issue by rolinger** [driftyco/ionic-creator-issues#217]
Similar to "ionic start [appName] creator:xxxxxxxx", which downloads an existing project from Creator and starts a new local project, there should be a way to start a local project and then upload it to Creator for the ability take advantage of the tools.

ie: c:\code\newApp> ionic creator upload

**Comment by matthewkremer** [comment]
Hey @rolinger,

This is probably one of the absolute hardest things for us to accomplish, verging on impossible, since we have no idea what your local project looks like. Instead, we're thinking about adding in-Creator code editors in the future to edit controllers, etc.

Thanks,
Matt
