### ISSUE TITLE
Undo/Redo Option? and some of my suggestions

### ISSUE THREAD

**Issue by haze007** [driftyco/ionic-creator-issues#221]
I couldn't find the option to undo/redo the things I do at Ionic Creator. Also I'd love to see things like Logic Builder, RSS feed generator tool,  so it becomes a full app creation tool. I tried creating a Todo list app with Ionic creator itself (I know it's crazy but I just tried to do things that any newbie would expect). Opening the local directory on Ionic Creator would be uber cool as well ;)

**Comment by matthewkremer** [comment]
Hey @haze007,

You can undo redo with the standard keyboard shortcuts for most things.

In the future we will be adding more and more features to Creator, starting with the major release from Tuesday. We hope to make it even more than a prototyping tool as we progress :)

Thanks,
Matt
