### ISSUE TITLE
Prototyping only?

### ISSUE THREAD

**Issue by pmsteil** [driftyco/ionic-creator-issues#231]
It seems that this tool at this point is only for wireframing/prototyping and not full out design of an app.  The lack of ability to add CSS to any element, resize elements, place any element anywhere you want, etc makes it very limiting.  

Is this by design and do you want me to add Issues for these types of things that I think need to be added?

**Comment by matthewkremer** [comment]
Hey @pmsteil,

Yes, right now our focus is primarily on prototyping, but we are definitely open to adding features to make it easier and take the tool further. CSS editing is one of those really awesome ones that I think we should add :+1: 

As I focus on getting the current tool more and more stable, we'll be able to take some of these crazy ideas and put them into action :wink:

Thanks for the input, and please let me know any other bugs or usability concerns you find.

- Matt

**Comment by pmsteil** [comment]
Ok, thanks...
