### ISSUE TITLE
Swiping

### ISSUE THREAD

**Issue by pmsteil** [driftyco/ionic-creator-issues#232]
Is there an ability to mockup how a user might swipe left/right to get to a new page?  Is that even possible with ionic?

**Comment by matthewkremer** [comment]
Hey @pmsteil,

Nothing like that in Creator right now, but if you're interested in checking it out here are some resources you can look at for Ionic:

Swipe to go Back Feature:
http://blog.ionic.io/rc0-swipe-to-go-back/

Documentation for ``onGesture`` which you could use to detect swiping and change pages manually
http://ionicframework.com/docs/api/utility/ionic.EventController/#onGesture
(Some conversation on this: http://forum.ionicframework.com/t/swipe-for-page-transition/1390/12)

Thanks,
Matt

**Comment by pmsteil** [comment]
Thanks!
