### ISSUE TITLE
Can't add icons to button bar

### ISSUE THREAD

**Issue by shaulhadar** [driftyco/ionic-creator-issues#236]
Hi Matthew, I tried to make a button bar that will have an icon button, but there is no place to choose the icon.. please add the ionicons icons to the button bar...
Thanks :)

**Comment by matthewkremer** [comment]
Icons have been added to buttons now :+1:

**Comment by shaulhadar** [comment]
Wow Matthew , you work fast man! thanks for this :)

**Comment by shaulhadar** [comment]
Just noticed that if you add any element after putting the icons in the button bar, it will reset all the icons in the bar, please fix this...

Thanks

**Comment by matthewkremer** [comment]
Hey @shaulhadar,

I'm not seeing this, could you explain the steps to reproduce a little further for me? Also, let me know what browser you're using.

Thanks,
Matt

**Comment by shaulhadar** [comment]
Hi Matthew...
what i did is add a button bar, than i put an icon and chose for instance assertive class.
Than i added the spacer element, and it restarted the button bar..

I checked this on latest firefox by the way..
Let me know if you need me to check anything else..

**Comment by shaulhadar** [comment]
here is my project i tested it on:

http://creator.ionic.io/app/designer/093cf1331609

Thanks...
