### ISSUE TITLE
Cannot edit input boxes, keys trigger other actions

### ISSUE THREAD

**Issue by willbittner** [driftyco/ionic-creator-issues#238]
Reproduce
1. Create a new app
2. Add a tabs screen
3. Try and change the Title on the Tab screen to "Site Editor" 
you will see around S, or E or so that you begin to fire actions on random items in the GUI (almost like a ctrl key is stuck) and lose focus on the input box.

**Comment by willbittner** [comment]
Seems to maybe "search by name" in the pages box while editing the text input

**Comment by matthewkremer** [comment]
Ah, I think I might know what's going on here. I'm in the middle of upgrading some other things, but I'll definitely look into this.

**Comment by kylefox** [comment]
This is quite frustrating and basically makes the Creator app unusable. As soon as I type a single character into a text field the app forces my focus elsewhere, meaning I have to click back into the text field after every single character.

**Comment by matthewkremer** [comment]
This was an issue that was fixed in the major release of Creator on Tuesday. Please check it out and let me know what you think!

Thanks,
Matt
