### ISSUE TITLE
My app in Ionic Lab says nothing but back

### ISSUE THREAD

**Issue by mmpco** [driftyco/ionic-creator-issues#243]
When ever I click index.html or when I try testing it on Ionic Lab all that is says is back.  I don't know whats wrong but if any of you could help me that would be awesome.

**Comment by matthewkremer** [comment]
Hey @mmpco,

Are you talking about after you've exported your app from Creator? If so, I just pushed a fix for this.

You may need to edit your app in Creator (add a button, then delete it) to cause a Save to fire, then re-export and you should be good.

Let me know if it works for you!

Thanks,
Matt
