### ISSUE TITLE
Some icons don't appear.

### ISSUE THREAD

**Issue by rodrigograca31** [driftyco/ionic-creator-issues#244]
As you can see in this image some of the icons don't appear when chosen.....
There are several of them that don't work....

![Icon?](http://i.imgur.com/S3spoWJ.png)

**Comment by matthewkremer** [comment]
This was an issue that was fixed in the major release of Creator on Tuesday. Please check it out and let me know what you think!

Thanks,
Matt

**Comment by rodrigograca31** [comment]
Yes, it's fixed. But the icon I had disappeared... I had to chose a new one... (Not a problem to me because I was just testing...)
