### ISSUE TITLE
Side menu heading and list-item not updating

### ISSUE THREAD

**Issue by snbhanja** [driftyco/ionic-creator-issues#245]
Hello

I am creating a side menu prototype using creator.
I have changed the side menu heading, but it doesn't shows in preview of app.
Similar issues with list-items also.

The browser I am using is Google chrome Version 43.0.2357.130 m (64-bit)
![image](https://cloud.githubusercontent.com/assets/3896278/8552143/db2e40d4-24f8-11e5-9d64-55fb3f1114e3.png)

**Comment by matthewkremer** [comment]
Side-menus were removed from the latest release of Creator. The editing experience was subpar. We will be revisiting this once we determine a better editing experience that actually works :)
