### ISSUE TITLE
Button-Bar unable to select last button

### ISSUE THREAD

**Issue by gekosurf** [driftyco/ionic-creator-issues#246]
Ive added extra button to button-bar and im unable to select the last button that was added

**Comment by seand88** [comment]
also happening to me.
It appears when you create a new button bar, the last added button somehow gets a reference to a button on another selected page. Its very strange, some kind of reference/memory issue

**Comment by matthewkremer** [comment]
This was an issue that was fixed in the major release of Creator on Tuesday. Please check it out and let me know what you think!

Thanks,
Matt
