### ISSUE TITLE
Links not showing when create more than one modal page

### ISSUE THREAD

**Issue by lucashattori** [driftyco/ionic-creator-issues#247]
I am not getting any links list in the drop-down, so i discovered that it happens when I create more than one modal page. I really need have more than one

**Comment by Pitouli** [comment]
Same issue!
The issue is perhaps that we cannot name the modal?

**Comment by daveyjones** [comment]
I need more than one modal too...

**Comment by matthewkremer** [comment]
Modal was removed from the newest release of Creator. It just had too many things wrong with it. We will be revisiting and adding it back in later once we determine a better editing experience :)
