### ISSUE TITLE
No landscape support

### ISSUE THREAD

**Issue by amberau** [driftyco/ionic-creator-issues#249]
Not a bug, but for prototyping it's really important to have a landscape mode. Thanks!

**Comment by seeps001** [comment]
I agree with @amberau. Any indication on when landscape might be supported?

**Comment by rochasdv** [comment]
Yes, is a bug because do not did what it's supposed to do. Design in landscape mode is very necessary....without landscape mode I can't start my project (that will be a app in landscape mode locked).

**Comment by matthewkremer** [comment]
This is definitely something that will be coming soon :)

**Comment by nbgkbn** [comment]
Any word on Landscape?

**Comment by matthewkremer** [comment]
This has already been added, just click on the "Rotate" icon next to the % scale above the preview.
