### ISSUE TITLE
Ionic Creator Links not showing pages

### ISSUE THREAD

**Issue by scorrin** [driftyco/ionic-creator-issues#250]
I have several pages set up.  I have placed buttons on each of the pages.  When I go to the link drop list there is nothing there and the other pages are not listed.  So, with 4 pages in the app I am unable to have any buttons link between them.  Same issue with a button bar, the only item in the link list is "not linked".  I tried several browsers and removed all history and found no resolution to the issue.

**Comment by hectorlagocarrera** [comment]
I have the same issue. Any solution? thank you

**Comment by scorrin** [comment]
No, I have not had resolution to this issue yet :(  I have stopped using it as I need this things to work as it is a showstopper if you can't link pages. Tried different browsers and different computers to eliminate issues on my end, so it is either my account that is the issue or something with the creator itself. If you find a solution let me know...

**Comment by jacobleecd** [comment]
I have the same issue. 

After placing a button and clicking "link" on the right to link it to another page, only the "not linked" option is available, preventing me from linking it. I added other pages in case that was a prerequisite, both inside and outside a Card, and on multiple pages. Tried on both current versions of chrome and ie.

**Comment by arilla** [comment]
i have discovered if any page not contains 'URL setting' cannot link to any other!, just set te first page to "/" in the URL setting. hope this help!

**Comment by gvreddys99** [comment]
page not contains 'URL setting' cannot link to any other! or multiple pages contain same url  Links not showing

**Comment by matthewkremer** [comment]
This was an issue that was fixed in the major release of Creator on Tuesday. Please check it out and let me know what you think!

Thanks,
Matt
