### ISSUE TITLE
Infinite loop causing UI instability and inconsistency in loading elements

### ISSUE THREAD

**Issue by arashz** [driftyco/ionic-creator-issues#251]
![screen shot 2015-07-30 at 11 56 05 am](https://cloud.githubusercontent.com/assets/782945/8992172/06ee22d2-36b2-11e5-925d-b12c7093e3a4.png)

When using the creator.ionic.io on a specific project and in the process of dragging and dropping elements in to form section there is somehow an issue which is causing the ui code to run in an infinite loop. The issue appears to be happening at the ion-creator.js line 4509 

![screen shot 2015-07-30 at 11 59 25 am](https://cloud.githubusercontent.com/assets/782945/8992265/720a5e3c-36b2-11e5-80ac-c9b0a69123ae.png)

This appears across both chrome and safari browsers as far as I've seen.

**Comment by arashz** [comment]
Specifically the element being checked on line 4509 is $(this).val() but when checked the  $(this) is referring to a select box where none of the elements are selected by default this the value would always be null. Think the fix would be to add by default at least an element pre selected or better yet remove the check.



![screen shot 2015-07-30 at 12 04 49 pm](https://cloud.githubusercontent.com/assets/782945/8992489/9757cca0-36b3-11e5-8907-bd378cda9b53.png)

![screen shot 2015-07-30 at 12 07 19 pm](https://cloud.githubusercontent.com/assets/782945/8992485/91052906-36b3-11e5-9421-439ad9b1589c.png)

![screen shot 2015-07-30 at 12 07 30 pm](https://cloud.githubusercontent.com/assets/782945/8992492/9a9e7f3a-36b3-11e5-9e60-c36bd91bf509.png)

**Comment by matthewkremer** [comment]
This was an issue that was fixed in the major release of Creator on Tuesday. Please check it out and let me know what you think!

Thanks,
Matt
