### ISSUE TITLE
test view shows black 

### ISSUE THREAD

**Issue by machail** [driftyco/ionic-creator-issues#257]
All that I dragged onto the page was a spacer, a heading and a little form

This is how it should look

![image](https://cloud.githubusercontent.com/assets/5968963/9640974/8ebd4b62-51b4-11e5-9657-d1129041bb37.png)

And this is how it looks

![image](https://cloud.githubusercontent.com/assets/5968963/9640941/5d417d6a-51b4-11e5-967d-7723013edff5.png)

**Comment by jmarceli** [comment]
+1

**Comment by matthewkremer** [comment]
A major release was pushed on Tuesday, please confirm that this no longer happens for you.

Thanks,
Matt

**Comment by jmarceli** [comment]
It seems to be solved I don't get black screen anymore.

**Comment by matthewkremer** [comment]
Thanks @jmarceli ! I appreciate you taking the time to check for me.
