### ISSUE TITLE
First page of a blank app has no URL which makes linking of pages not possible

### ISSUE THREAD

**Issue by MilenaMMay** [driftyco/ionic-creator-issues#259]
Steps:

When starting a blank app, the first page has no URL.
Insert a second page and put a button on any of those pages. 
Click on the Link property of the button.
The only available option is "Not Linked", even though there is another page.

---

Fix:

Insert `/` into the Routing URL property of the first page.
The Link property of the Button now contains all selectable pages.

---

Could you preset the Routing URL property of the first page of a blank app with `/`, please?

**Comment by MilenaMMay** [comment]
Sorry, just realized this is a duplicate:

https://github.com/driftyco/ionic-creator-issues/issues/250

**Comment by matthewkremer** [comment]
No longer applicable due to major update of Ionic Creator. Please check it out and let me know what you think!

Thanks,
Matt
