### ISSUE TITLE
Tabs Icons

### ISSUE THREAD

**Issue by okjedi** [driftyco/ionic-creator-issues#26]
It's possible to set most icons, but then when going to test, they disappear, leaving only the text below the icon.

**Comment by matthewkremer** [comment]
I've pushed a partial fix for this that will allow you to rechoose an icon instead of the page freaking out. Still working on an actual fix. Stay tuned!

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
