### ISSUE TITLE
When buttons are selected they link incorrectly, makes app unusable 

### ISSUE THREAD

**Issue by seand88** [driftyco/ionic-creator-issues#260]
There is a major issue with selecting buttons in the app

When selecting the button as seen here. It is selecting the wrong button in the list.
When I select the button on Page B, it links back to a button on Page A.
Changing the button on pageB also changes the actually text of the button on Page A.

These buttons should not be linked together and makes it almost possible to create interfaces in the app because as you are editing one page its changing another. 

Refreshing does not fix the issue. it can be reproduced by just clicking around buttons on another page...

This screenshot has my workout page button selected, but you can see in the list on the left its highlighting another button
Also shows wrong text in the editor.

http://prntscr.com/8cmn3x

**Comment by matthewkremer** [comment]
This seems like it may be an ID issue. If you delete the button that is causing the issue and recreate it, does the problem go away?

Also, the team and I are in the process of making a huge update, and a lot of stuff is fixed in it :+1: 

Thanks,
Matt

**Comment by matthewkremer** [comment]
No longer applicable due to major update of Ionic Creator. Please check it out and let me know what you think!

Thanks,
Matt
