### ISSUE TITLE
Buttons, Cards, Markdown Text all link incorrectly

### ISSUE THREAD

**Issue by jonmc12** [driftyco/ionic-creator-issues#264]
I was playing with Ionic creator last night.  After a while it seems like just about every element would become associated with some other element on some other page.

I tried deleting and recreating items;  dragging items into other items; changing the sequencing of adding items; doing a hard refresh of page.  There was really no way to use the app after a certain point.

One reproducible issue I found: create a new blank page and add 10 cards.  The 11th card will link to the wrong element. 

The other major correlation seemed to be that adding a new Markdown Text box, for instance, would link to the most recently added Markdown Text box.

**Comment by matthewkremer** [comment]
There was a major release on Tuesday that I believe fixed this. If it still happens, please let me know!

Thanks,
Matt
