### ISSUE TITLE
Renaming project doesn't update recent projects list

### ISSUE THREAD

**Issue by birbilis** [driftyco/ionic-creator-issues#270]
I make a new project named test, then I press top right (rails) button to open the right sidebar and rename the project. Beneath that section a Projects section is shown with recent projects. There though the project keeps on being named test (at the top of the pane the new name is shown ok). Clicking on that recent "test" project it reloads and now it shows the name OK in that (recent projects) list if I open it up again

**Comment by matthewkremer** [comment]
No longer applicable due to major update of Ionic Creator. Please check it out and let me know what you think!

Thanks,
Matt

**Comment by birbilis** [comment]
At what version was the update? How can I check what version I'm using in case there's something cached? I see other issues too I plan to report (eg new page action doesn't select it at sidebar), but want to be sure I see the new system you mention first

**Comment by matthewkremer** [comment]
Do a hard refresh just to make sure. But this version has a new projects dashboard, teams, etc that you should see when you login :)

**Comment by birbilis** [comment]
indeed, there is no such list now - other issues I had seen still stand though, will file separate issues for them

**Comment by matthewkremer** [comment]
Thanks @birbilis! I appreciate it :)
