### ISSUE TITLE
Ionic Creator app not found Error 

### ISSUE THREAD

**Issue by theartsnetwork** [driftyco/ionic-creator-issues#275]
I have been testing Ionic Creator for scaffolding my new app and I made one but when I tried to build a project with Ionic CLI - ionic start [app name] creator:b099a62c8e2e

it is giving me following error, Please help. 

$ ionic start [app name ] creator:b099a62c8e2e
Creating Ionic app in folder /Users/username/[App name based on app] project
Downloading: https://github.com/driftyco/ionic-app-base/archive/master.zip
[=============================]  100%  0.0s
Downloading: https://github.com/driftyco/ionic-starter-v1]/archive/master.zip
[=============================]  100%  0.0s
 ✗ Not found: https://github.com/driftyco/ionic-starter-v1]/archive/master.zip (404)
 ✗ Please verify the url and try again.
Please verify you are using a valid URL or a valid ionic starter.
View available starter templates: `ionic templates`
More info available at: 
http://ionicframework.com/getting-started/
https://github.com/driftyco/ionic-cli

It has created a blank app in the directory but I would like it to be the app I created with Creator instead.

**Comment by theartsnetwork** [comment]
Also tried creating another app and then - Ionic Start but still it is giving the same error!

**Comment by matthewkremer** [comment]
We're aware of this and have been working on a fix, should be out soon!

**Comment by matthewkremer** [comment]
Hey @theartsnetwork,

We pushed a fix for this. Make sure you update your local Ionic CLI by running ``npm install -g ionic`` and try it again for me!

Thanks,
Matt

**Comment by theartsnetwork** [comment]
Hi Matthew, It seems the error is consistent even after I updated the CLI. I tried with both my apps and no luck.

**Comment by birbilis** [comment]
- is that directory empty at first?
- is there a chance the pathname is too long? (though I guess you're not trying on Windows since you write $ for prompt)
- is there possibility it doesn't have rights to write the stuff in the directory?

**Comment by matthewkremer** [comment]
Hey @theartsnetwork,

Are you able to download the ZIP file from the dashboard?

Thanks,
Matt

**Comment by theartsnetwork** [comment]
Hi @matthewkremer, 
It worked! I had to update the CLI once again before I could successfully scaffolded the app. 
Thanks you and IONIC team for awesome tools and resources! 
Best. 

Aks
