### ISSUE TITLE
Can't select the right button when multiple buttons are in different levels of the same page

### ISSUE THREAD

**Issue by cesarlugosis** [driftyco/ionic-creator-issues#285]
I added buttons within a couple item-list inside a list (using a list-item-with-thumbnail), then I added buttons outside the list within the same page, then I tried to select one of them by clicking on it, but it selects the other button within the list instead. Also tried selecting the button from the menu list in the upper left section and same thing happens, it selects the wrong button instead.

**Comment by matthewkremer** [comment]
This should be fixed with the duplicate ID bug fix I just pushed!  You may have to delete the offending buttons, but it shouldn't happen again in the future.

**Comment by cesarlugosis** [comment]
Yes it works now, thank you. Is there a way to delete the offending button? I cant select it. If not, I could just re-build that page. Thank you!

**Comment by matthewkremer** [comment]
You may have to delete both offending buttons. AKA click the one that links to the other, and delete the other one.
