### ISSUE TITLE
Clone a page

### ISSUE THREAD

**Issue by birbilis** [driftyco/ionic-creator-issues#287]
Controls in pages have a Clone/Duplicate (see you call it Duplicate [for projects] at the dashboard) button, but Pages in the Tree don't have such. It would be very useful, especially since I can't copy controls now from one page to the other 

Say I have a button bar that I have configured with icons and colors with add/edit/remove buttons, I don't want to created every time from scratch at every page that uses it. A quick way to help around this is to add page cloning, which would also be useful for someone to make a page in their project, configure it with headers/footers as they like (especially if you add support for adding controls at the header/footer), then clone it many times to make the other pages of the project look alike

**Comment by IJsLauw** [comment]
+1

**Comment by birbilis** [comment]
I see this has been implemented now, nice
