### ISSUE TITLE
Menu, Toggle settings in Safari 8

### ISSUE THREAD

**Issue by blackshuu** [driftyco/ionic-creator-issues#29]
"Toggle settings" is not working as expected when using Safari 8.

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10) AppleWebKit/600.1.25 (KHTML, like Gecko) Version/8.0 Safari/600.1.25

![menu_settings_toggle](https://cloud.githubusercontent.com/assets/4109330/4552177/f1297bd0-4e7d-11e4-93ce-3f37fb738511.png)

![menu_settings_toggle2](https://cloud.githubusercontent.com/assets/4109330/4552218/9fdfc58a-4e7e-11e4-8753-a42b14c4d0fe.png)

**Comment by matthewkremer** [comment]
This seems to work well for me now, may be related to my fix for #78. I'm going to close this, but let me know if you're still having the issue :+1: Thanks!
