### ISSUE TITLE
Corruption of content

### ISSUE THREAD

**Issue by birbilis** [driftyco/ionic-creator-issues#295]
I have https://creator.ionic.io/share/c3ca7ca7e823 (made this for http://schoolprojectmanager.codeplex.com/) and I'm trying at the designer to add a page to it, but it seems that as I add a 2nd button to that new page, a button from another page gets selected instead. If I don't delete that new page and try to edit that button, the button of the other page will be edited. It's driving me crazy.

Is there any way I can share a test copy of that project with you to try it out and see what's happening? (is this maybe possible via the teams feature?). I don't see any way to allow others to clone your project in their own dashboard

If we could export to JSON or XML the project, then I could check what looks strange in the resulting tree and maybe fix it by hand and reimport it back (see issue already posted about that suggestion)

**Comment by birbilis** [comment]
if some admin can access my dashboard, please play arround or copy to your dashboard the project "TESTING School Project Manager" (6d55ade81353). THIS IS A CLONE JUST FOR YOUR TESTING

**Comment by IJsLauw** [comment]
Same problem here, added a few pages and they got mixed up with my my with tabs, now everything is broken. (admin let me know if you need details...)

**Comment by birbilis** [comment]
If you select the new page from the tree bottom, then press delete page at the right side of the screen, the tree gets fixed (before that other places in the tree show the title of the new page)

**Comment by birbilis** [comment]
If you add page again same thing happens. Tried cloning project, but same happens at clone. Made a new test project with many pages but issue didn't happen there. Had seen sometimes message that project is open elsewhere too (? Hanging browser instance maybe?) and had pressed yes at question to save changes. Maybe that does the corruption?

**Comment by matthewkremer** [comment]
Going to try to look into this one today. @birbilis Was this a project that you created in the new version of creator? Or was it one that was "leftover" from the old version?

Thanks,
Matt

**Comment by matthewkremer** [comment]
@IJsLauw Could you get me the ID (URL) from that project that got messed up with tabs? Thanks!

**Comment by birbilis** [comment]
There's a chance I had started it at the previous version. Does it keep any info on first creation date or other history?

Btw, having way to undo would be nice. Also to backup/restore to a human readable json or xml file. Now only way to feel more safe is to create project clones often and give them some time stamp in the name. 

If the project could be exported/imported to a description file could even do git integration maybe (check in changes, rollback...)

**Comment by matthewkremer** [comment]
This is merely an ID issue. I have a fix ready that hard-checks whether or not IDs exist (the buttons linking together both have the same ID). It will be in the next push to production :+1:

**Comment by IJsLauw** [comment]
That would be: ae43708e2b0b

On 28 Oct 2015, at 15:52, Matthew Kremer <notifications@github.com<mailto:notifications@github.com>> wrote:


@IJsLauw<https://github.com/IJsLauw> Could you get me the ID (URL) from that project that got messed up with tabs? Thanks!

**Comment by birbilis** [comment]
nice to hear it @matthewkremer - since this is a stopping issue, any info on when the fix is going to go live?

**Comment by matthewkremer** [comment]
@birbilis @IJsLauw Have to look into something tomorrow morning before we can push the fix live, we broke something else. But all you'll have to do to fix your old projects is delete the button that's giving you the issue and recreate it. I'll ping you guys when it's live.

**Comment by matthewkremer** [comment]
@birbilis @IJsLauw Alright, the fix has been pushed to production! Please delete any button that was giving you an issue and recreate. Let me know if you encounter this again :)

**Comment by birbilis** [comment]
@matthewkremer not sure it is exactly "fixed". I'd expect some automated process to fix all such controls with empty IDs (if I get it correctly) either at project load, or once for all projects in your database. It would assign them some random unique id I guess (not sure if the control IDs are unique per page or per project btw)

when I opened my problematic project and tried to add new page at some points it started flashing that dialog that says the project is opened in other place and asking whether to keep changes (had shown that before, but never flashing it). I use Mozilla btw. I pressed Cancel instead of Save this time but kept on showing it, had to press Save eventually.

Later on it started doing similar issues as before (not being able to delete buttons or selecting them would select button of other page in the tree) with some buttonbars (those same ones must have been doing the issue before) and I had to remove those buttonbars (couldn't remove the problematic button in them) and add and set them up again which takes sometime, especially if you have to remove button labels, set style and add icons...
...(it's a pitty one can't export subtrees to JSON/XML to make templates that they would be able to reimport again - could even show such templates in the control toolbox of a project [that one could select to make global for all their projects with some star button on them or something] or even a have global template gallery for users to share such templates and get ones they like into a project's toolbox)

btw, at some point before I deleted those buttonbars it started saying "Error saving changes" and I just closed the project (went to dashboard) and back into it again but kept on saying the same till I removed those two buttonbars (from two different pages). Seeing that message you feel helpless since it has no feedback, plus you can't export the project or do something else to not lose changes. Hope those errors are logged somewhere so that you can check them. They occured at the same https://creator.ionic.io/share/c3ca7ca7e823 project. Now it is working fine I hope

**Comment by matthewkremer** [comment]
Hey @birbilis,

We haven't written a database script to automatically fix the projects yet, so right now it's just deleting and recreating the buttons or whatever is causing the issue. The fix we pushed should prevent duplicate IDs from happening again.

The Save dialog is meant to prevent two people from having the project opened or having two tabs with the same project open at the same time. If it pops up and you're the only one in the project, just hit the "Save" button and it shouldn't bug you again (unless you refresh, etc).

Templates and saving portions of the tree is an idea we have on the list already.

If you encounter "Error saving changes" again, could you open developer tools and let me know if an error came back with the save request?

**Comment by birbilis** [comment]
btw see https://github.com/driftyco/ionic-creator-issues/issues/288 - I think that may have caused the issue with the blank IDs in the first place

**Comment by birbilis** [comment]
just had the "Error saving changes" again. Tried to remove some buttonbars I had created, but wasn't sure what was causing it (didn't see anything strange happening with selecting items as before). So I went back to the dashboard and cloned the project, renamed and then opened the clone. Opening it it said error saving changes, but pressing Save myself it did save ok. Then went back to the original one and pressing SAVE myself (the clock icon) it did save ok too. I had opened the dev tools (Firefox) but didn't see anything strange (just some logging that didn't seem like errors) at every failed save actions (the first time it happened it was showing something, but I didn't pay attention to it unfortunately and tried to press Save at which point it didn't appear again - maybe it was unrelated though)

**Comment by birbilis** [comment]
rushed to say all is ok now - I have a form (Student Info) where I try to add a heading (all is saved), then I add a list (can't save), then I remove the list (STILL CAN'T SAVE!), then I remove the heading too (SAVES)

**Comment by birbilis** [comment]
just managed to repeat a save error by making new page, dropping in a heading, a buttonbar, a heading, a buttonbar, then dropped buttons on the first buttonbar (while it was already saving, maybe that causes such errors?), I see  [HTTP/1.1 500 Internal Server Error] logged

**Comment by birbilis** [comment]
...there is a chance I had added the page and then forgot to select that page in the tree, but started editing its title instead. I have already reported this strange behaviour (not selecting the new page in the tree once it's added) and it maybe that is causing the problem
