### ISSUE TITLE
Hard to identify a project's clone from original one on the dashboard

### ISSUE THREAD

**Issue by birbilis** [driftyco/ionic-creator-issues#305]
May have reported this already but can't find it (probably was saying this in some other issue's discussion, so posting it at a separate issue:

Cloning a project seems to add the clone to the left instead of to the right of the project you cloned on the dashboard, making you think the one at the right is the clone. That way you may accidentally damage the original (the URL of which you may have already shared with others to view) when you just want to tinker with the clone. Only way to see which one is the original is to press download or share and see the id shown there. 

Apart from changing it to add the new one to the right of the original one (instead of to the left [or even order it depending on RTL setting for Arabic etc. locales]), maybe also show the project id or add a number to the clone's name (incrementing it till it gets a unique name on the dashboard)

**Comment by matthewkremer** [comment]
Fixed by adding Clone to title.
