### ISSUE TITLE
Scrolling down a long page in designer with scrollwheel takes ages

### ISSUE THREAD

**Issue by birbilis** [driftyco/ionic-creator-issues#317]
I have a long page and although it scrolls ok in the preview, in the designer using the mouse wheel it scrolls too slow in Firefox. It shows a very thin scrollbar when I do it that I can't drag, neigher can I drag the page up/down from some empty space of it

**Comment by hemgui** [comment]
Same issue on firefox 42
Scroll is very slow with gesture on touchpad and even worse with mouse scroll.

**Comment by hemgui** [comment]
fix on my side when issue #254 has been solved

**Comment by mlynch** [comment]
:dancers:

**Comment by matthewkremer** [comment]
Shoutout to @mlynch for the fix on this one :+1:
