### ISSUE TITLE
All code in one file?

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-creator-issues#33]
I believe this is a change from yesterday, but I noticed in the Raw HTMl, Zip export that the code is all in index.html. While that definitely simplifies things, not having an app.js separated means developers will have to (well, should) separate this out manually when they get the code.

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt

**Comment by cfjedimaster** [comment]
I said this on Slack but want it public too - I am *incredibly* happy with the updated source code export.
