### ISSUE TITLE
Can't add radio button options to existing radio button group

### ISSUE THREAD

**Issue by nikmartin** [driftyco/ionic-creator-issues#333]
Ionic Bot closed this, but it is still broken: 
#140

**Comment by EduardoNE** [comment]
please, give more infos

**Comment by matthewkremer** [comment]
Hey @nikmartin and @EduardoNE :)

I'm not quite sure what you mean, you can drag in more Radio buttons from the component section and it seems to work just fine for me.

Can you clarify? Maybe I'm misunderstanding.

**Comment by nikmartin** [comment]
I can't replicate it now, but when I reported it, every time i tried to drag a button onto an existing radio, it would create a new radio group, vs adding the button to the existing group.

**Comment by matthewkremer** [comment]
Strange, let me know if it pops up again! Thanks :)
