### ISSUE TITLE
perf: I want to upload my project on ionic creator.

### ISSUE THREAD

**Issue by adamdbradley** [driftyco/ionic-creator-issues#336]
_From @DaGeTian on February 14, 2016 20:22_

**Type**: <span ionic-type>perf</span>

**Ionic Version**: <span ionic-version>2.x</span>

**Platform**: <span ionic-platform>mobile</span>  <span ionic-webview>webview</span>

<span ionic-description>It's not bug. I want to upload my project(www) on ionic creator and continue develop. Because I changed some forms with my code. But i can't use it on ionic creator.</span>

<span is-issue-template></span>

_Copied from original issue: driftyco/ionic#5450_

**Comment by matthewkremer** [comment]
Hey @dagetian,

Thanks for reaching out! Building an import feature into Creator would be extremely difficult as we'd have to parse code no matter how the developer wrote it.

However, adding code editing abilities for Controllers, Services, CSS and more directly into Creator is definitely on our roadmap.
