### ISSUE TITLE
Markdown/HTML Not Rendered Correctly

### ISSUE THREAD

**Issue by cawoodm** [driftyco/ionic-creator-issues#338]
This may be a CSS issue but standard unordered lists and italics are not rendered at all. This is the case for Paragraphs (Markdown) and HTML components.

![creator 2](https://cloud.githubusercontent.com/assets/498834/13675263/129d20c6-e6e1-11e5-8b60-406be09bbc61.png)
![creator 1](https://cloud.githubusercontent.com/assets/498834/13675264/12b85cf6-e6e1-11e5-9f21-c8e8c6ab2ecf.png)

**Comment by matthewkremer** [comment]
Ionic overwrites UL styling by default. Check out this for more information :)

http://stackoverflow.com/questions/22743852/how-to-display-a-bullet-list-using-ionic-framework
