### ISSUE TITLE
Link to external URL clears relative links

### ISSUE THREAD

**Issue by cawoodm** [driftyco/ionic-creator-issues#339]
When developing an app in the creator I want to link to some "external" but local resources. So say I want something like href="/myfiles/something.ppt".

I can enter /myfiles/something.ppt in the link section if I choose "External URL" but it silently clears it when I navigate away. It should at least give a warning but better would be to allow the user to decide which URLs they want and just leave it be.

![creator 3](https://cloud.githubusercontent.com/assets/498834/13675383/9ddf678e-e6e1-11e5-877a-c5d1efbbe6cd.png)

**Comment by matthewkremer** [comment]
Should be fixed, thanks for reporting!
