### ISSUE TITLE
page ID - change filename from default page14.html

### ISSUE THREAD

**Issue by webonix** [driftyco/ionic-creator-issues#34]
will it be possible to set the ID (name) of a page?

```
    .state('page14', {
      url: '/page-two',
      templateUrl: 'page14.html'
    })

<script id="page14.html" type="text/ng-template">
```

![image](https://cloud.githubusercontent.com/assets/217567/4570425/ae6b5544-4f5d-11e4-8c23-f8080772836e.png)

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
