### ISSUE TITLE
Button bar individual buttons resize when select

### ISSUE THREAD

**Issue by hollyschinsky** [driftyco/ionic-creator-issues#39]
After I add a button bar, if I select an individual button it resizes to fill to where the selection box for the button bar selects and stays that way after. In the 2nd screenshot I had previously clicked on the 1st and 3rd buttons. The style also changes in the UI to display *block* and *stable*  versus *inline* and *light* but the source code ends up looking like:

       <div class="button-bar">
            <button class="button  ">1</button>
            <button class="button button-stable button-block">2</button>
            <button class="button  ">3</button>
        </div>

![button-bar](https://cloud.githubusercontent.com/assets/359935/4571064/6d480526-4f6c-11e4-86a6-d06ea3543b39.png)
![buttonbar3](https://cloud.githubusercontent.com/assets/359935/4571065/6d49610a-4f6c-11e4-937c-8f6a92c6e385.png)

**Comment by matthewkremer** [comment]
Hey @hollyschinsky,

I've recently joined the Ionic team and am in the process of going through the issues list for Creator.

I tried to recreate this but it seems to be working fine for me, could you please confirm if this is still an issue for you?

Thanks!
Matt
