### ISSUE TITLE
page 3 on new app

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-creator-issues#5]
I built a new app, added a button bar on top. I have no pages except the default one made with the new project. When I click a button and select the Link drop down, I see

Page (page3)

Where did page3 come from? I'm assuming some default label, but the 3 seems weird.

**Comment by matthewkremer** [comment]
I've updated it to restart the ID list when creating a new project, this should fix any drastic jumps in numbers (I could get it to "start" at 7+ before).

You'll still start on page3 if you start with a default page and Login page at the moment though. Once I sift through the issues list more I may come back to this to make it a little more intuitive.

Thanks!
