### ISSUE TITLE
Cannot focus sidemenu view

### ISSUE THREAD

**Issue by kcdipesh** [driftyco/ionic-creator-issues#58]
In the sidemenu template it is not  possible to see the preview of side-menu so dragndrop of components does not work. The preview always shows content of the side-menu-content

**Comment by benjaminb10** [comment]
+1 @WarrenHobden 
It's not so intuitive.
A focus on the view when we click on the side bar item in the views list will be a better toggle to reveal the view.

**Comment by matthewkremer** [comment]
We've actually removed that page type for right now. The editing experience was sub-par and buggy. We're talking about how to make complicated editing cases like this better, and will most likely be adding it back in in the future.

Thanks,
Matt
