### ISSUE TITLE
Feature Request: Use Image as a button

### ISSUE THREAD

**Issue by ncunning** [driftyco/ionic-creator-issues#65]
Would it be possible to use an image as a button within the creator?
Especially thinking around navigation image buttons.
I'm thinking of either an SVG image (to allow for scaling) or base64 encoding an image and using the string as the src attribute of an image.

This would allow for designing nicer user interfaces.

Simple example. 

![image](https://cloud.githubusercontent.com/assets/2520318/4754438/f34b43c0-5abd-11e4-848e-4f0ab723671e.png)

**Comment by mleoking** [comment]
+1

**Comment by mlynch** [comment]
This was added a while back but there was an issue that was just resolved. Please give it another go :)
