### ISSUE TITLE
Feature Request: Add new / extra tab

### ISSUE THREAD

**Issue by rvanbaalen** [driftyco/ionic-creator-issues#66]
After removing a tab, there is no (easy) way to re-add a tab.

Possibly combine this with a maximum of three tabs per tabbed interface (disable ability to add tab when max is reached).

Mentioned in #26

**Comment by felipecocco** [comment]
Is there a way to add any tabs beyond the specified 3 at this point?

**Comment by creativesprite** [comment]
Struggling to add a 4th tab to the bottom tab bar, is 3 the limit ?

**Comment by matthewkremer** [comment]
Added this in :+1: 

Just click on your page that contains tabs, then click on the "tabs" element in the left sidebar and you should see a button on the right that says "Add New Tab" :smile:
