### ISSUE TITLE
Blank screen in test mode

### ISSUE THREAD

**Issue by vaibhavn1** [driftyco/ionic-creator-issues#69]
Hi team,

When i change the mode to test mode , the screen is not showing my pages and show this blank page.

![screen](https://cloud.githubusercontent.com/assets/4082467/4769513/107643ce-5b7b-11e4-87da-7b40cd62d575.png)

Regards

Vaibhav

**Comment by unselected** [comment]
Same here , blank screen in test mode , when i went back into edit mode the screen i was working on was white , i had to nav to another screen i had worked on and back to the original to get it to not show white.
How is there no response on this thread yet , seems like a pretty important issue?

**Comment by matthewkremer** [comment]
I may have fixed this this morning, could you confirm whether or not this is still an issue? Thank you!

**Comment by YamilG** [comment]
I think I found the problem; make sure in the **ROUTING URL** you're including "/" before your name.

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
