### ISSUE TITLE
New page "linking" to old page

### ISSUE THREAD

**Issue by hanicker** [driftyco/ionic-creator-issues#73]
After adding many pages, if I add a new one to my project and I click on it I see the content of one of the old pages I created. If I edit it, I change both my old and new page. After checking with developer tools, I see new created page has same id of an old one.

Refreshing doesn't fix.

![bug](https://cloud.githubusercontent.com/assets/510258/4783797/3f1501ae-5d36-11e4-9d07-f75f47977128.png)

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

You may have to delete some pages or create a new project, as this was an ID issue.

Thanks,
Matt
