### ISSUE TITLE
Right site menu not scrolling

### ISSUE THREAD

**Issue by matheusbaumgart** [driftyco/ionic-creator-issues#78]
Hello, the menu on the right side is not scrollable. 

![screen shot 2014-10-28 at 9 09 35 am](https://cloud.githubusercontent.com/assets/4028897/4798611/7ff3877e-5e15-11e4-8863-f31d92ea4e11.png)

I'm using Safari.

**Comment by matthewkremer** [comment]
Fixed this! Please let me know if you continue to have this issue :+1:
