### ISSUE TITLE
Blank New Page edits the page currently working on

### ISSUE THREAD

**Issue by mrmwiebe** [driftyco/ionic-creator-issues#79]
Occasionally when creating a new blank page, a blank page appears in the "pages" panel on the left, but when clicked on, it's not blank, but shows the contents of the page I was currently working on.  

Furthermore, if I had been working on Page A when I clicked the new page button, the new page (we'll call it Page B) will be created in the "pages" pane, but the contents shown in the editor shows the content of Page A.  Plus, Page A will now be named "page" and any edits while Page B is selected will edit the contents of Page A.

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
