### ISSUE TITLE
list thumbnail item does not have a link property

### ISSUE THREAD

**Issue by alokkulkarni389** [driftyco/ionic-creator-issues#84]
list item with Thumbnail does not have a link property which does not allow you to proceed in the navigation with detail screen if you want to show that.

**Comment by jannone** [comment]
Noticed that one too. +1

**Comment by c0bra** [comment]
:+1:

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
