### ISSUE TITLE
Forgetting to put / in front of routing URL prevents preview

### ISSUE THREAD

**Issue by nconroy** [driftyco/ionic-creator-issues#87]
I made a new login page and gave it a routing url of "login"
When I previewed I got a dark overlay but nothing else.
Changing the routing URL to "/login" fixed the issue.
Might be good to have some validation on this field.

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
