### ISSUE TITLE
Exporting project second time not working

### ISSUE THREAD

**Issue by romuloctba** [driftyco/ionic-creator-issues#88]
Opening because #47 is already closed

This is happening to me right now. I'll update the page and try again:
didn't work:
```
GET http://localhost:8100/css/preview-frame.css  (index):46

GET http://localhost:8100/css/preview-frame.css  (index):46

GET http://localhost:8100/lib/ionic.css  (index):47

GET http://localhost:8100/lib/ionic.bundle.js  

Uncaught ReferenceError: angular is not defined (index):65(anonymous function) (index):65
```

i guess the right paths should have `/lib/ionic/`  + `js` or + `/css`

*Worth saying that first I used the cli to download the project, and then I tried to just paste the HTML*

If i paste only what's between `<body></body>` it works fine. 
I'm guessing just correcting the paths should fix the problem

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
