### ISSUE TITLE
How to add header bar on Side Menu page?

### ISSUE THREAD

**Issue by ghost** [driftyco/ionic-creator-issues#91]
I have added a new Side Menu page but I am unable to find any option to add header bar to it. Like, how can I add title?

**Comment by stefalda** [comment]
+1

**Comment by sameermaira** [comment]
+1

**Comment by matthewkremer** [comment]
We've actually removed that page type for right now. The editing experience was sub-par and buggy. We're talking about how to make complicated editing cases like this better, and will most likely be adding it back in in the future.

Thanks,
Matt
