### ISSUE TITLE
Preview shows a blank black screen

### ISSUE THREAD

**Issue by reflog** [driftyco/ionic-creator-issues#92]
Console shows:

Uncaught ReferenceError: google is not defined angular-google-maps-1.1.10.min.js:7
Identifying 13 components ionic-creator.js?8:2
Can't find any component with id app1 ionic-creator.js?8:3
Couldn't identify component for app1 ionic-creator.js?8:2

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
