### ISSUE TITLE
Changing pages url break existing links

### ISSUE THREAD

**Issue by mcampo** [driftyco/ionic-creator-issues#95]
If I change the routing url of a page, all links linking to it get set to "Not linked". It would be nice if those links point to the new url after the change.

As a bonus, it would also be nice if the links show the page name instead of the url (in the select box).

**Comment by matthewkremer** [comment]
This has been fixed in the new major release of Creator on Tuesday. Please let me know if you still encounter any issues!

Thanks,
Matt
