### ISSUE TITLE
Tab icons can't display on the web browser window

### ISSUE THREAD

**Issue by daikonbuu** [driftyco/ionic-creator-issues#98]
## Overview
Tab icons can't display on the web browser window because we can't scroll the browser window.
Tab page has three tabs and icons on bottom of page
but we can't select them.
The contents of tab page is long but scroll bar is hidden.

## Step of reproduction
1. Start new project
2. Added the new tab page to use "Add page" button.
3. Finish to create new tab page
4. Can't scroll

### Web Browser
Chrome v38 for mac
## Display resolution
1366 x 768 (MacBook Air 11inc)

**Comment by matthewkremer** [comment]
This should be fixed now, please let me know if you're still having this issue! :+1:
