### ISSUE TITLE
Modal Pages can't be renamed

### ISSUE THREAD

**Issue by JacerOmri** [driftyco/ionic-creator-issues#99]
I've been able to change any page's name except for modal pages, it just shows one option, to remove it.

**Comment by lucashattori** [comment]
+1

**Comment by matthewkremer** [comment]
We've actually removed that page type for right now. The editing experience was sub-par and buggy. We're talking about how to make complicated editing cases like this better, and will most likely be adding it back in in the future.

Thanks,
Matt
